### ISSUE TITLE
Miko's Armory

### ISSUE THREAD

**Issue by Hydra7-1** [ThatCoolSnek/Gun-Research-Overhaul#10]
https://steamcommunity.com/sharedfiles/filedetails/?id=3045145179&searchtext=miko+armory
Yo Snek, when you get the chance could you look into adding this mod?

**Comment by ThatCoolSnek** [comment]
its "Yo Snek The Swiftie" to you, smh my head. yeah ill have it done in a day or 2

**Comment by ThatCoolSnek** [comment]
done
