### ISSUE TITLE
New Gtek's Combat Extended Arsenal Update

### ISSUE THREAD

**Issue by LegitGamer1017** [ThatCoolSnek/Gun-Research-Overhaul#11]
Gtek has new update that adds some new guns. 

https://steamcommunity.com/sharedfiles/filedetails/changelog/3035243918

"Massive Update. still not v2.0, that's taking longer than I thought, but I still decided that in order to make up for the long break between last update I will release some of what I have so far. Includes many new weapons that I couldn't show in one Steam preview image, so I have posted a preview for the new weapons free on my Ko-Fi page linked in the description (make sure to click the hi-res button).

Added:
- Ohio Ordnance REAPR
- Knights Armament LAMG
- AK-103
- M4A1 Block I
- SA-58 IBR
- Remington M870 Tactical
- Remington M700
- And many more rare variants!

Changed:
- Many textures have been replaced/cleaned up, I forgot which ones though.
- SA-58 IBW no longer craftable, as the IBR is basically just better for 90% of this game's combat.
- Certain weapons now have specific WeaponTags assigned to them, for the people who make custom factions with my guns. I plan to tag most of them in the future.
- Semi-Automatic civilian versions of military rifles no longer spawn on Elite Pirate Mercenaries.
- Many sounds were tweaked slightly to sound better in-game. Added a unique sound for the Thompson SMG."

Will this require the patch to be updated?

**Comment by ThatCoolSnek** [comment]
mr gtek himself manages the patches for Gun Research Overhaul so i will ask him to update them

**Comment by ThatCoolSnek** [comment]
mr gtek told me that theyre patched for GRO. if u have proof that theyre not or that the patches r bugged or something please go to him about it. thank you

**Comment by ThatCoolSnek** [comment]
i just saw that u asked if they need a patch update. oopsie >.<. yeah it should be all good according to gtek
