### ISSUE TITLE
important do not forget

### ISSUE THREAD

**Issue by Alfafits** [ThatCoolSnek/Gun-Research-Overhaul#2]
https://steamcommunity.com/sharedfiles/filedetails/?id=2694371667 (adds some cool guys)
https://steamcommunity.com/sharedfiles/filedetails/?id=2981554547 (adds c4)
https://steamcommunity.com/workshop/filedetails/?id=2412382876

**Comment by ThatCoolSnek** [comment]
not really doing explosives (yet)
