### ISSUE TITLE
patch requests

### ISSUE THREAD

**Issue by Holli-Git** [ThatCoolSnek/Gun-Research-Overhaul#3]
https://steamcommunity.com/sharedfiles/filedetails/?id=2563506048
https://steamcommunity.com/sharedfiles/filedetails/?id=2980844330
https://steamcommunity.com/sharedfiles/filedetails/?id=3082592693
https://steamcommunity.com/sharedfiles/filedetails/?id=2563504596 
https://steamcommunity.com/sharedfiles/filedetails/?id=2563507593
https://steamcommunity.com/sharedfiles/filedetails/?id=1650070060

**Comment by ThatCoolSnek** [comment]
im not patching ur own god damn firearm research mod

**Comment by ThatCoolSnek** [comment]
u clearly cant read aswell cuz guns galore is being patched by its dev. learn to fucking read

**Comment by Holli-Git** [comment]
> u clearly cant read aswell cuz guns galore is being patched by its dev. learn to fucking read

so ur patching rimmunation thank you <3

**Comment by ThatCoolSnek** [comment]
y dont u just use ur own mod?
