### ISSUE TITLE
Compatibility for Rimmu-Nation.

### ISSUE THREAD

**Issue by PestArzt1936** [ThatCoolSnek/Gun-Research-Overhaul#8]
Rimmu-Nation - Weapons mod( https://steamcommunity.com/sharedfiles/filedetails/?id=2563507593 ) is a mod with many different guns. I find that mod good balanced and pleasure looking that's why i prefer to use it in almost every my mod pack. I think, that mod deserve compatibility with Gun-research-Overhaul mod.
(Frankly speaking, I didn't know what should i write in the description. Excuse me for my incompetence. Consequently, I believe that you would do this, despite my description.)

**Comment by ThatCoolSnek** [comment]
u can just list the mod. i started work on the patch but i stopped because of personal reasons + wanting to get the mod out. i shall finish it and put it in within a couple days.

**Comment by ThatCoolSnek** [comment]
working on it now, should be done in a few hours

**Comment by ThatCoolSnek** [comment]
rimmunation has been patched, thanks for ur patience.
