### ISSUE TITLE
Guns Galore

### ISSUE THREAD

**Issue by JeffChislett** [ThatCoolSnek/Gun-Research-Overhaul#9]
If compatibility with the Guns Galore series of mods(https://steamcommunity.com/workshop/filedetails/?id=2949320350) could be implemented when you have time, that would be greatly appreciated.

**Comment by ThatCoolSnek** [comment]
step 1. learn how to read
step 2. read the description of my mod
step 3. apologize to me

**Comment by JeffChislett** [comment]
I did not know Guns Galore was getting patched internally.
